# Generated by Django 4.1.1 on 2022-10-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="gender",
            field=models.CharField(
                choices=[("F", "Female"), ("M", "Male")], max_length=10
            ),
        ),
    ]
