# Generated by Django 4.1.1 on 2022-10-14 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0002_alter_employee_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("starting_from", models.DateTimeField()),
                (
                    "duration_type",
                    models.IntegerField(choices=[(1, "Hours"), (2, "Days")]),
                ),
                ("duration", models.SmallIntegerField()),
                ("reason", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_requests",
                        to="employee.employee",
                    ),
                ),
                (
                    "substitute",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="substitute_accountabilities",
                        to="employee.employee",
                    ),
                ),
            ],
        ),
    ]
