# Generated by Django 4.1.1 on 2022-10-07 18:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_deliverable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliverable",
            name="weight",
            field=models.IntegerField(
                blank=True,
                default=1,
                validators=[
                    django.core.validators.MaxValueValidator(100),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
        ),
    ]
